version: '3.8'

services:
  dev:
    container_name: nestjs_graphql_test_server
    image: nestjs-graphql-test-server:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
